server:
  port: 8080

elasticsearch:
  host: localhost
  port: 9200

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/webc2c-dev
    username: root
    password: root
